# Generated by Django 3.2.7 on 2022-08-14 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_option_poll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='host',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
    ]
