# Generated by Django 3.2.7 on 2022-08-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_option_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
