# Generated by Django 3.2.7 on 2022-08-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_poll_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='has_poll',
            field=models.BooleanField(default=False),
        ),
    ]
